#! /bin/bash
set -eux

docker build -t allprogrammic/openresty-bundle-deb .
CONTAINER=$(docker create allprogrammic/openresty-bundle-deb)
if [ ! -d ./artifacts ]; then
    mkdir ./artifacts
fi
docker cp $CONTAINER:/build/openresty_1.9.15.1~allprogrammic+1.0_amd64.deb ./artifacts/
docker rm $CONTAINER
