#! /bin/bash
set -eux

docker build -t allprogrammic/openresty-bundle-deb .
CONTAINER=$(docker create allprogrammic/openresty-bundle-deb)
if [ ! -d ./artifacts ]; then
    mkdir ./artifacts
fi
docker cp $CONTAINER:/build/openresty_*-tapstream1_amd64.deb ./artifacts/
docker rm $CONTAINER
